# Generated by Django 5.1 on 2024-08-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a book title', max_length=100, unique=True)),
                ('author', models.CharField(max_length=64)),
                ('summary', models.TextField(max_length=300)),
                ('pages', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('isbn', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
            ],
        ),
    ]
