# Generated by Django 5.1 on 2024-08-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='uploaded_images'),
        ),
    ]
