# Generated by Django 5.1 on 2024-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
